package com.google.code.yourpresenter;

public enum YpError {
	SLIDE_ID_NOT_SET, MEDIA_CRAWLING_FAILED, THUMBNAIL_CREATION_FAILED, PREFERENCE_NOT_SET, DEFAULT_PREFERENCES_LOADING_FAILURE, FILEOBJECT_NAME_ERROR, FILE_READING_FAILED, EMPTY_DROP_VALUE, NOT_SUPPORTED_IDX, AJAX_PUSH_ERROR, PREFERENCES_NOT_SET, JSON_SERIALIZATION_FAILED;
}
