package com.google.code.yourpresenter;

public enum YpError {
	SLIDE_ID_NOT_SET, MEDIA_CRAWLING_FAILED, THUMBNAIL_CREATION_FAILED, PREFERENCE_NOT_SET, DEFAULT_DATA_LOADING_FAILURE, FILEOBJECT_NAME_ERROR, FILE_READING_FAILED, EMPTY_DROP_VALUE, NOT_SUPPORTED_IDX, AJAX_PUSH_ERROR, PREFERENCES_NOT_SET, JSON_SERIALIZATION_FAILED, ROLE_NOT_SUPPORTED, METHOD_NOT_IMPLEMENTED, PREFERENCE_NOT_SPECIFIED, INVALID_PDF_PAGES_INTERVAL, FILE_IMPORT_FAILED, EXEC_FAILED, SONG_DELETE_FAILED;
}
