package com.google.code.yourpresenter;

public enum YpError {
	SLIDE_ID_NOT_SET, MEDIA_CRAWLING_FAILED, THUMBNAIL_CREATION_FAILED, PREFERENCE_NOT_SET, DEFAULT_PREFERENCES_LOADING_FAILURE, FILEOBJECT_NAME_ERROR, THUMBNAIL_READING_FAILED, EMPTY_DROP_VALUE;
}
